#ifndef TESTUICONTROLLER_GLOBAL_H
#define TESTUICONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTUICONTROLLER_LIBRARY)
#  define TESTUICONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTUICONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTUICONTROLLER_GLOBAL_H
